proto/config/routes.rb
Proto::Application.routes.draw do
  get "casham/index"
  get "cashams", to: "casham#index"
  get "casham/tcl"
  get "casham/tcc"
  get "casham/ocl"
  get "casham/occ"
  get "casham/localstore"
  get "casham/store_locator"
  get "casham/store_locator_simple"
  get "casham/pawn_loans"
  get "tim/index"

  root 'tim#index'

  

end

proto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

proto/app/controllers/ca_controller.rb
class CaController < ApplicationController
  def index
  end

  def tcl
  end

  def tcp
  end
end

proto/app/controllers/casham_controller.rb
class CashamController < ApplicationController
  layout false
  before_action :get_params

  def index
  end

  def tcl
  	render layout: "two_column_landing"
  end

  def tcc
  	render layout: "two_column_content"
  end

  def ocl
  	render layout: "one_column_landing"
  end

  def occ
  	render layout: "one_column_content"
  end

  def store_locator
    @services = ["Pawn Loans", "Auto Equity Loan", "Cash Advance", "Preowned Merchandise", "Check Cashing", "Prepaid Debit Cards", "Money Orders", "Insurance", "Gold Purchase", "Money Transfer", "Income Tax" ]
    @brands = ["Cash America", "SuperPawn", "Cashland", "Payday Advance"]
    render layout: "one_column_content"
  end

  def store_locator_simple
    @services = ["Pawn Loans", "Auto Equity Loan", "Cash Advance", "Preowned Merchandise", "Check Cashing", "Prepaid Debit Cards", "Money Orders", "Insurance", "Gold Purchase", "Money Transfer", "Income Tax" ]
    @brands = ["Cash America", "SuperPawn", "Cashland", "Payday Advance"]
    render layout: "one_column_content"
  end

  def pawn_loans
    render layout: "two_column_content"
  end

  protected
    def get_params

        @search_class = params[:search_class]

    end
end

proto/app/controllers/tim_controller.rb
class TimController < ApplicationController
  def index
  end
end

proto/app/helpers/application_helper.rb
module ApplicationHelper
end

proto/app/helpers/ca_helper.rb
module CaHelper
end

proto/app/helpers/casham_helper.rb
module CashamHelper
end

proto/app/helpers/tim_helper.rb
module TimHelper
end

proto/app/views/casham/components/_landing_hero.html.erb
<% headline_text = "Cash America Headline" if local_assigns[:headline_text].nil? %>

<div class="page-hero">
  <div class="row page-hero-container">
    
      
    <% if cols == "eight" %>
      
      <div class="eight columns offset-by-four page-headline-container">
    
    <% else %>
    
      <div class="twelve columns page-headline-container">
    
    <% end %>


      <h1 class="page-headline"><%= headline_text %></h1>

      <ul class="breadcrumbs">
        <li>
          <a href="#">Home</a></li>
        
        <li>
          <a href="#">Features</a></li>
        
        <li class="unavailable">
          <a href="#">Gene Splicing</a></li>
        
        <li class="current">
          <a href="#">Home</a></li>
      </ul>
    </div>
  </div>
</div>

proto/app/views/casham/components/_widget_content_article.html.erb
<section class="widget content-article row">
    <div class="twelve columns">
        <h2>
            <a href="#">Article Title</a>
        </h2>
    </div>

    <div class="twelve columns">
        <span class="article-image-right">
            <%= image_tag "pawn3.png" %>
        </span>

        <p>While your item is in pawn, you still own it. Your item is safely stored until you come back to pay your pawn loan in full and claim your merchandise. When you give us an item of collateral for pawn, we keep all accessories (remote controls, cables, etc.) with your item, and place it in our secure facility in an area designated by your pawn loan number. All Cash America shops are fully insured for the total loan value of the collateral we keep.</p>

        <p>Our coworkers are professionals who are trained in all aspects of the pawn industry, including extensive education on the products we receive and sell. They are required to complete several continuing education courses each year, and attend additional educational courses each quarter as new products/services are implemented in our pawnshops. Cash America coworkers take pride in their work and it shows—from their consistent dress code to the way they greet customers and confidently handle pawn transactions—they are professionals who are ready to help.</p>

        <p>Our pawnshops are routinely audited by an Internal Audit & Security Department, and work closely with local law enforcement officials.
        </p>
    </div>
</section>

proto/app/views/casham/components/_widget_financial_planning.html.erb
<section class="widget financial-tools row ">
  <div class="twelve columns">
    <h1 class="widget-header  ">
      Financial Planning Tools
    </h1>
  </div>
    
  <div class="widget-body twelve columns">
    <div class="list-widget-item row">
      <div class="three mobile-one columns">
        <%= image_tag "budget.png" %>
      </div>
      
      <div class="nine mobile-three columns">
        <p class="lead">Take control of your finances with our budget worksheet</p>
        <p class="description">For many of us, budgeting is difficult to do. We struggle to make ends meet, but never seem to make enough progress to reach financial independence. This worksheet is designed to help you gain control of your finances and features an easy five-step system to create a budget that you can live with.</p>
        
        <a href="#" class="button">Create a budget</a>
      </div>
    </div>
    <hr/>
    <div class="list-widget-item row">
      <div class="three mobile-one columns">
        <%= image_tag "financial-education.png" %>
      </div>
      
      <div class="nine mobile-three columns">
        <p class="lead">Learn to manage your money with our financial education program</p>
        <p class="description">Cash America is committed to financial education and consistently work to educate customers, coworkers and communities about money management.</p>

        <p class="description">
        Visit the Financial Education Program websites to 
        view videos, read articles and utilize other tools on the websites to learn how to easily manage your money.</p>
        
        <a href="#" class="button">Start Learning</a>
      </div>
    </div>
  </div>
</section>

proto/app/views/casham/components/_widget_pr_highlights.html.erb
<section class="widget list-widget pr-highlights row ">
  <div class="twelve columns">
    <h1 class="widget-header  ">
      PR Highlights
    </h1>
  </div>
    
  <div class="widget-body twelve columns">
    <div class="list-widget-item row">
      <div class="three mobile-one columns">
        <img src="http://placehold.it/160x160">
      </div>
      
      <div class="nine mobile-three columns">
        <p>Article Title: Subhead consisting of about eight to ten words</p>
      </div>
    </div>

    <div class="list-widget-item row">
      <div class="three mobile-one columns">
        <img src="http://placehold.it/160x160">
      </div>
      
      <div class="nine mobile-three columns">
        <p>Article Title: Subhead consisting of about eight to ten words</p>
      </div>
    </div>

    <div class="list-widget-item row">
      <div class="three mobile-one columns">
        <img src="http://placehold.it/160x160">
      </div>
      
      <div class="nine mobile-three columns">
        <p>Article Title: Subhead consisting of about eight to ten words</p>
      </div>
    </div>
  </div>
</section>

proto/app/views/casham/components/_widget_service_spotlight.html.erb
<section class="widget features-widget service_spotlight row">
  <div class="twelve columns">
    <h1 class="widget-header">
      We Also Provide These Great Services
    </h1>

    <ul class="widget-body block-grid four-up mobile-two-up">
      <li>      
        <div class="service-item">
            <%= image_tag "pawn3.png", {width: 75} %>
            <p class="caption"><a href="#">Pawn Loans</a></p>
          </div>
      </li>
      
      <li>
        <div class="service-item">
          <%= image_tag "auto-equity.png", {width: 75}  %>
          <p class="caption"><a href="#">Auto Equity Loans</a></p>
        </div>
      </li>
      
      <li>
        <div class="service-item">
          <%= image_tag "cash-advances.png", {width: 75} %>
          <p class="caption"><a href="#">Cash Advances</a></p>
        </div>
      </li>
      
      <li>
        <div class="service-item">
          <%= image_tag "retail-services.png", {width: 75} %>
          <p class="caption"><a href="#">Retail Services</a></p>
        </div>
      </li>
    </ul>
    <div class="widget-footer">
      <p class="caption"><a href="#">View all of our services</a></p>
    </div>
  </div>
</section>

proto/app/views/casham/components/_widget_store_locator.html.erb
    <section class="widget store-locator row">
      <div class="twelve columns">
        <h1 class="widget-header">
          <span aria-hidden="true" data-icon="&#xe02f;" class="icon icon-location-17-icon"></span><a href="" class="text">Find a Store Near You</a>
        </h1>

        <div class="row collapse widget-body">
          <div class="nine mobile-three columns">
            <input type="text" placeholder="Zip or City and State"/>
          </div>
          
          <div class="two mobile-one columns">
            <a href="<%= casham_store_locator_simple_path %>" class="button expand postfix radius submit">Go</a>
          </div>
        </div>
      </div>
    </section> <!-- end widget -->

proto/app/views/casham/components/_your_store.html.erb
<div class="your-store-dropdown">
    <div class="local-store">
        <div class="control">
          <a>
              <span aria-hidden="true" data-icon="&#xe02b;" class="icon icon-arrow-right control-icon"></span> </a>
        </div>
        <address class="store-address full-address">
            <ul>
              <li class="small-label">Your Store:</li>
              <li class="store">Cash America</li>
              <li class="street">1234 Street Address</li>
              <li class="province">Farmington, CT 12345</li>
              <li class="tel">Phone:<a href="tel:408-867-5309">408-867-5309</a> </li>
            </ul>
        </address>
        <div class="divider"></div>
        <div class="store-hours">

            <span>Store Hours</span>
            <table>
                <%# for i in 1...7 %>
                <% ['Mon', 'Tues', 'Wed','Thurs','Fri','Sat','Sun'].each do |day| %>
                <tr>
                    <td class="day">
                        <%= day %>
                    </td>
                    <td class="hours">
                        88:88am - 88:88pm
                    </td>
                </tr>
                <% end %>
            </table>
        </div>
    </div>
    <div class="options">
        <ul>
            <li><a>Show on Map</a></li>
            <li><a>View Store's Website</a></li>
            <li><a>Change Your Store</a></li>
        </ul>
    </div>
    <div class="store-address-list">
        <% for i in 1...5 %>
        <address class="store-address">
            <ul>
                <li class="store">
                    <span><%= i %>. </span> Brand - Store Number
                </li>

                <li class="street">
                    Street Addresss NW 7th
                </li>

                <li class="province">
                    Ft Worth, Tx 75000
                </li>

                <li class="tel">
                    Phone:<a href="tel:408-867-5309">408-867-5309</a>
                </li>
           </ul>
        </address>
        <% end %>
    </div>
</div>

proto/app/views/casham/index.html.erb
Cash America Layouts

<ul>
	<li>
		<%=link_to "Two Column Landing", casham_tcl_path %>
	</li>

	<li>
		<%=link_to "Two Column Content", casham_tcc_path %>
	</li>

	<li>
		<%=link_to "One Column Landing", casham_ocl_path %>
	</li>

	<li>
		<%=link_to "One Column Content", casham_occ_path %>
	</li>
</ul>

proto/app/views/casham/menutest.html.erb
<% content_for :head do %>
    <%= render "casham/structure/head", page_css: ["components/header"] %>
<% end %>


<% content_for :main_content do %>

    
   <style>
    #megaStore {
        width: 600px;
        margin: 30px auto;
        padding-top: 120px;
        background-color: lightBlue;
    }
    #menu h2 {
        font-size: 1em;
        text-transform: uppercase;
        padding: 5px 10px;
    }
    #template img {
        margin: 5px 20px 0 0;
        float: left;
    }
    #template {
        width: 380px;
    }
    #template ol {
        float: left;
        margin: 0 0 0 30px;
        padding: 10px 10px 0 10px;
    }
    #template:after {
        content: ".";
        display: block;
        height: 0;
        clear: both;
        visibility: hidden;
    }
    #template .k-button {
        float: left;
        clear: left;
        margin: 5px 0 5px 12px;
    }
</style>

    <div id="example" class="k-content">
        <div id="megaStore">
            <ul id="menu">
                <li>
                    Products
                    <ul>
                        <li>
                            Furniture
                            <ul> <!-- moving the UL to the next line will cause an IE7 problem -->
                                <li>Tables & Chairs</li>
                                <li>Sofas</li>
                                <li>Occasional Furniture</li>
                                <li>Childerns Furniture</li>
                                <li>Beds</li>
                            </ul>


                        </li>
                        <li>
                            Decor
                            <ul> <!-- moving the UL to the next line will cause an IE7 problem -->
                                <li>Bed Linen</li>
                                <li>Throws</li>
                                <li>Curtains & Blinds</li>
                                <li>Rugs</li>
                                <li>Carpets</li>
                            </ul>
                        </li>
                        <li>
                            Storage
                            <ul> <!-- moving the UL to the next line will cause an IE7 problem -->
                                <li>Wall Shelving</li>
                                <li>Kids Storage</li>
                                <li>Baskets</li>
                                <li>Multimedia Storage</li>
                                <li>Floor Shelving</li>
                                <li>Toilet Roll Holders</li>
                                <li>Storage Jars</li>
                                <li>Drawers</li>
                                <li>Boxes</li>
                            </ul>

                        </li>
                        <li>
                            Lights
                            <ul> <!-- moving the UL to the next line will cause an IE7 problem -->
                                <li>Ceiling</li>
                                <li>Table</li>
                                <li>Floor</li>
                                <li>Shades</li>
                                <li>Wall Lights</li>
                                <li>Spotlights</li>
                                <li>Push Light</li>
                                <li>String Lights</li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    Stores
                    <ul>
                        <li>
                            <div id="template" style="padding: 10px;">
                                <h2>Around the Globe</h2>
                                <ol>
                                    <li>United States</li>
                                    <li>Europe</li>
                                    <li>Canada</li>
                                    <li>Australia</li>
                                </ol>
                                <img src="../../content/web/menu/map.png" alt="Stores Around the Globe" />
                                <button class="k-button">See full list</button>
                            </div>
                        </li>
                    </ul>
                </li>
                <li>
                    Blog
                </li>
                <li>
                    Company
                </li>
                <li>
                    Events
                </li>
                <li disabled="disabled">
                    News
                </li>
            </ul>
        </div>


    </div>
<% end %>

proto/app/views/casham/occ.html.erb
<% content_for :head do %>
	<%= render "casham/structure/head" %>
<% end %>

<% content_for :header do %>
	<%#= render "casham/structure/header" %>
<% end %>

<% content_for :hero do %>
	<%= render "casham/components/landing_hero", cols: "twelve"  %>
<% end %>

<% content_for :main_content do %>
	<div class="twelve columns main-body tcc-page" role="content"> <!-- Main Content -->

<% 
=begin %>  
		
		<%= render "casham/components/widget_service_spotlight" %>
		
<% 
=end %>		
	</div>
<% end %>

<% content_for :footer do %>
	<%= render "casham/structure/footer" %>
<% end %>

proto/app/views/casham/ocl.html.erb
<% content_for :head do %>
	<%= render "casham/structure/head", page_css: ["components/header"] %>
<% end %>

<% content_for :header do %>
	<%= render "casham/structure/header" %>
<% end %>

<% content_for :hero do %>
	<%= render "casham/components/landing_hero", cols: "twelve"  %>
<% end %>

<% content_for :main_content do %>
	<main class="twelve columns main-body tcc-page" role="content"> <!-- Main Content -->
		<%#= render "casham/components/widget_service_spotlight" %>
	</main>
<% end %>

<% content_for :footer do %>
	<%= render "casham/structure/footer" %>
<% end %>

proto/app/views/casham/pawn_loans.erb
<% content_for :head do %>
    <%= render "casham/structure/head", page_css: ["pages/store_locator"] %>
<% end %>

<% content_for :header do %>
    <%= render "casham/structure/header" %>
<% end %>

<% content_for :hero do %>
    <%= render "casham/components/landing_hero", cols: "eight", headline_text: "Pawn Loans" %>
<% end %>


<% content_for :main_content do %>
    <!-- Sidebar -->
    <aside class="four columns side-bar pawn-loans-page">
        <div class="side-bar-container">

        <%= render "casham/components/widget_store_locator" %>
        <%= render "casham/components/widget_pr_highlights" %>
        <%= render "casham/components/widget_financial_planning" %>

        </div>
    </aside> <!-- End Sidebar -->



    <section class="eight columns main-body pawn-loans-page" role="content"> <!-- Main Content -->
            
        <div class="widget content-article row">
            <div class="twelve columns">
                <h3>
                    <a href="#">We Have Cash When it Counts</a>
                </h3>
            </div>

            <div class="twelve columns">
                <span class="article-image-right">
                    <%= image_tag "pawn3.png" %>
                </span>

                <p>We are one of the largest pawnshop chain in America with over 600 pawnshops operating under the names Cash America Pawn and SuperPawn. But don't let our size scare you—it just means we have more money to loan! If you’re in need of a short-term loan, but have never gotten a pawn loan before, let us walk you through the process.
                </p>
            </div>
        </div>

        <div class="widget content-article row">
            <div class="twelve columns">
                <h3>
                    <a href="#">It Really is as Easy as </a>
                </h3>
            </div>
            <div class="">
              <div class="eight columns">
                <p>We use all the research tools we have at our disposal to determine an item’s value and get you the most money we can. This appraisal process for a pawn item varies depending on the type of item—for example, jewelry is evaluated differently than a DVD player—but every appraisal is done with the intent of getting you the money you need.
                </p>
              </div>

              <div class="four columns">
                <%= image_tag "pawn3.png" %>
              </div>
            </div>
        </div>


        <div class="widget content-article row">
          <div class="twelve columns">
            <h3>
              <a href="#">How We Value Items</a>
            </h3>
          </div>
            <div class="">
              <div class="eight columns">
                <p>We use all the research tools we have at our disposal to determine an item’s value and get you the most money we can. This appraisal process for a pawn item varies depending on the type of item—for example, jewelry is evaluated differently than a DVD player—but every appraisal is done with the intent of getting you the money you need.
                </p>
              </div>

              <div class="four columns">
                <%= image_tag "pawn3.png" %>
              </div>
            </div>
        </div>

        <div class="widget content-article row">
            <div class="twelve columns">
                <h3>
                    <a href="#">How We Value Items</a>
                </h3>
            </div>

            <div class="twelve columns">
                <span class="article-image-right">
                    <%= image_tag "pawn3.png" %>
                </span>

                <p>While your item is in pawn, you still own it. Your item is safely stored until you come back to pay your pawn loan in full and claim your merchandise. When you give us an item of collateral for pawn, we keep all accessories (remote controls, cables, etc.) with your item, and place it in our secure facility in an area designated by your pawn loan number. All Cash America shops are fully insured for the total loan value of the collateral we keep.</p>

                <p>Our coworkers are professionals who are trained in all aspects of the pawn industry, including extensive education on the products we receive and sell. They are required to complete several continuing education courses each year, and attend additional educational courses each quarter as new products/services are implemented in our pawnshops. Cash America coworkers take pride in their work and it shows—from their consistent dress code to the way they greet customers and confidently handle pawn transactions—they are professionals who are ready to help.</p>

                <p>Our pawnshops are routinely audited by an Internal Audit & Security Department, and work closely with local law enforcement officials.
                </p>
            </div>
        </div>

        <%= render "casham/components/widget_service_spotlight" %>

    </section><!-- End Main Content -->
<% end %>

<% content_for :footer do %>
    <%= render "casham/structure/footer" %>
<% end %>

proto/app/views/casham/structure/_head.html.erb
  <% 
  
  page_css ||= []
  css_files = ["Reset", "Layout", "casham", "structure/structure", "skins/ca_skin"].concat(page_css) 

  %>
  <head>
    <meta charset="utf-8" />
    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width" />
    <title>Page Title</title>
    <!-- Included CSS Files -->

    <% css_files.each do |f| %>
    	<%= stylesheet_link_tag f.to_s %>
    <% end %>


    <%= javascript_include_tag "modernizr.foundation" %>
    <%= javascript_include_tag "application" %>
  </head>

proto/app/views/casham/structure/_header.html.erb
<header class="header">
  <div class="header-shade"></div> 

  <div class="row header-container">
    <div class="twelve columns">
      <nav class="top-bar">
        <ul>
          <li class="name"><h1><a href="#">Cash America</a></h1></li>
          <li class="toggle-topbar"><a href="#"></a></li>
        </ul>
        <div>
<!--           <ul class="left">
            <li><%= link_to "Home", cashams_path %></li>
          </ul> -->

          <ul class="left">
            <li><%= link_to "Pawn Loans", cashams_path %></li>
            <li><%= link_to "Auto Title Loans", cashams_path %></li>
            <li><%= link_to "Cash Advances", cashams_path %></li>
            <li><%= link_to "Store Locator", casham_store_locator_simple_path(:search_class => "inactive")%></li>
          </ul>          

          <ul class="your-store right">
            <li>
              <a><span aria-hidden="true" data-icon="&#xe02c;" class="icon icon-arrow-down-2 title"></span> </a>
            </li>
            <li>
              <div>Your Store:</div>
              <div>Cash America</div>
              <div>address</div>
            </li>
<% 
=begin %>  

            <li class="">
              <ul>
                <!-- <span aria-hidden="true" data-icon="&#xe02c;" class="icon icon-arrow-down-2 text-right"></span> -->
                <li class="org">Cash America</li>
                <li class="adr">
                  <a class="street-address">1234 Whodunnitst
                    <span class="locality">Ft. Worth, </span>
                    <span class="region">TX, </span>
                    <span class="postal-code">12345</span>
                  </a>
                </li>
              </ul>
            </li>

<% 
=end %>



        </ul>
          

        </div>      


      </nav>




<% 
=begin %>  
      
      <nav class="top-bar">


        <ul>
          <!-- Title Area -->
          <li class="name">
            <h1><a href="#">
                Cash America Logo Here
              </a></h1>
          </li>

          <li class="toggle-topbar">
            <a href="#"></a>
          </li>
        </ul>

        <section>
          <!-- Left Nav Section -->
          <ul class="left">
            <li class="divider"></li>

            <li class="has-dropdown">
              <a class="active" href="#">Item 1</a>

              <ul class="dropdown">
                <li><label>Section Name</label></li>

                <li class="has-dropdown">
                  <a href="#" class="">Level 1, Has Dropdown</a>

                  <ul class="dropdown">
                    <li>
                      <a href="#">Level 2</a>
                    </li>
                    
                    <li>
                      <a href="#">Level 2</a>
                    </li>

                    <li class="has-dropdown">
                      <a href="#">Level 2, Has Dropdown</a>
                      
                      <ul class="dropdown">
                        <li><label>Section</label></li>

                        <li>
                          <a href="#">Level 3</a>
                        </li>
                        
                        <li>
                          <a href="#">Level 3</a>
                        </li>
                        
                        <li class="divider"></li>
                        
                        <li>
                          <a href="#">Level 3</a>
                        </li>
                      </ul>
                    </li>

                    <li>
                      <a href="#">Level 2</a>
                    </li>

                    <li>
                      <a href="#">Level 2</a>
                    </li>
                  </ul>
                </li>

                <li>
                  <a href="#">Level 1</a>
                </li>

                <li>
                  <a href="#">Level 1</a>
                </li>

                <li class="divider"></li>

                <li><label>Section Name</label></li>

                <li>
                  <a href="#">Level 1</a>
                </li>
                
                <li>
                  <a href="#">Level 1</a>
                </li>
                
                <li>
                  <a href="#">Level 1</a>
                </li>
                
                <li class="divider"></li>

                <li>
                  <a href="#">See all &rarr;</a>
                </li>
              </ul>
            </li>
            
            <li class="divider hide-for-small"></li>
          </ul>

          <!-- Right Nav Section -->
          <ul class="right">
            <li class="divider show-for-medium-and-up"></li>

            <li class="has-dropdown">
              <a href="#">Item 2</a>
              
              <ul class="dropdown">
                <li><label>Section Name</label></li>

                <li>
                  <a href="#" class="">Level 1</a>
                </li>

                <li>
                  <a href="#">Dropdown Option</a>
                </li>
                
                <li>
                  <a href="#">Dropdown Option</a>
                </li>
                
                <li class="divider"></li>
                
                <li><label>Section Name</label></li>
                
                <li>
                  <a href="#">Dropdown Option</a>
                </li>
                
                <li>
                  <a href="#">Dropdown Option</a>
                </li>
                
                <li>
                  <a href="#">Dropdown Option</a>
                </li>
                
                <li class="divider"></li>
                
                <li>
                  <a href="#">See all &rarr;</a>
                </li>
              </ul>
            </li>
          </ul>
        </section>





      </nav>
<% 
=end %>
    </div>
  </div>
</header>

proto/app/views/casham/tcl.html.erb
<% content_for :head do %>
	<%= render "casham/structure/head", page_css: ["components/header", "structure/widget_store_locator"] %>
<% end %>

<% content_for :header do %>
	<%= render "casham/structure/foundation3_header" %>
<% end %>

<% content_for :hero do %>
	<%= render "casham/components/landing_hero", cols: "eight" %>
<% end %>


<% content_for :main_content do %>
	
	<main class="eight columns main-body push-four tcl-page" role="content"> <!-- Main Content -->	    
	    <p>main content</p>
	    <%#= render "casham/components/widget_service_spotlight" %>

	    <%= render "casham/components/widget_content_article" %>
	    <%= render "casham/components/widget_service_spotlight" %>
	    <%= render "casham/components/widget_store_locator" %>
	    <%= render "casham/components/widget_pr_highlights" %>
	    <%= render "casham/components/widget_financial_planning" %>

	</main><!-- End Main Content -->

	<!-- Sidebar -->
	<aside class="four columns pull-eight side-bar tcc-page">
		<h2 class="semantic-only">Related Content</h2>
	  <div class="side-bar-container">

	    <%= render "casham/components/widget_store_locator" %>
	    <%#= render "casham/components/widget_pr_highlights" %>

	    	    <%= render "casham/components/widget_content_article" %>
	    <%= render "casham/components/widget_service_spotlight" %>
	    <%= render "casham/components/widget_store_locator" %>
	    <%= render "casham/components/widget_pr_highlights" %>
	    <%= render "casham/components/widget_financial_planning" %>

	  </div>
	</aside> <!-- End Sidebar -->
<% end %>

<% content_for :footer do %>
	<%= render "casham/structure/footer" %>
<% end %>

proto/app/views/tim/index.html.erb
<h1>Hello world</h1>

<p>
	You are probably looking for 
	<%= link_to "this", casham_index_path %>	
</p>